In [1]:
import pandas as pd

df = pd.read_csv("Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [5]:
df['Name Length'] = df['Restaurant Name'].apply(lambda x: len(str(x)))
df['Address Length'] = df['Address'].apply(lambda x: len(str(x)))

df['Table_Booking_Flag'] = df['Has Table booking'].apply(lambda x: 1 if x.strip().lower() == 'yes' else 0)
df['Online_Delivery_Flag'] = df['Has Online delivery'].apply(lambda x: 1 if x.strip().lower() == 'yes' else 0)

df[['Restaurant Name', 'Name Length', 'Address Length', 'Table_Booking_Flag', 'Online_Delivery_Flag']].head()

,Restaurant Name,Name Length,Address Length,Table_Booking_Flag,Online_Delivery_Flag
0,Le Petit Souffle,16,71,1,0
1,Izakaya Kikufuji,16,67,1,0
2,Heat - Edsa Shangri-La,22,56,1,0
3,Ooma,4,70,0,0
4,Sambo Kojin,11,64,1,0

In [6]:
# Average rating by table booking flag
df.groupby('Table_Booking_Flag')['Aggregate rating'].mean()
# Average rating by name length group
df['Name Length Group'] = pd.cut(df['Name Length'], bins=[0, 10, 20, 30, 50], labels=['Short', 'Medium', 'Long', 'Very Long'])
df.groupby('Name Length Group')['Aggregate rating'].mean()

C:\Users\torah\AppData\Local\Temp\ipykernel_3896\2778598636.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Name Length Group')['Aggregate rating'].mean()

Name Length Group
Short        2.932316
Medium       2.563669
Long         2.529861
Very Long    2.943631
Name: Aggregate rating, dtype: float64